In [3]:
import pandas as pd

import numpy as np

import os

from ast import literal_eval

import glob

In [4]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\Downloads\*.xlsx') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\Downloads\Colt Manufacturing_Analyst Detail_2025May_2026April.xlsx

In [5]:
excel_file = pd.ExcelFile(latest_file)
sheet_names = excel_file.sheet_names

print(sheet_names)

['Analyst Detail']

In [6]:
df = pd.read_excel(latest_file)

In [7]:
df.columns

Index(['Company', 'Processor', 'Customer Code', 'Customer Name',
       'Customer Group Name', 'Multiple Invoice Indicator',
       'First TI Invoice Number', 'TI Invoice Number', 'Master Bill Number',
       'Pro Number',
       ...
       'Re-weigh Y/N', 'Reclassified Y/N', 'Questionable Data Y/N',
       'Multi-Stop Y/N', 'Not Ours to Pay', 'Copypayzero Y/N',
       'Expedited Bill Y/N', 'Guaranteed Bill Y/N', 'Masterbill Created User',
       'Masterbill Last Audit Clear User'],
      dtype='object', length=161)

In [16]:
import pandas as pd
import numpy as np

input_file = df   # change to your file name
output_file_wgt = "output_weights.xlsx"


# function to collect weights from each row
def collect_weights(row):
    weights = []
    for col in df.columns:
        if col.startswith("Average of Weight"):
            val = row[col]
            if pd.notna(val):
                weights.append(val)
    return weights

# create list of weights per row
df["all_weights"] = df.apply(collect_weights, axis=1)

# group by shipmentID and combine lists
grouped_wgt = df.groupby("Lane")["all_weights"].sum().reset_index()

# find max number of weights in any shipment
max_len = grouped_wgt["all_weights"].apply(len).max()

# expand into separate columns
for i in range(max_len):
    grouped_wgt[f"weight_{i+1}"] = grouped_wgt["all_weights"].apply(
        lambda x: x[i] if i < len(x) else np.nan
    )

# drop helper column
grouped_wgt = grouped_wgt.drop(columns=["all_weights"])

# save to Excel
grouped_wgt.to_excel(output_file_wgt, index=False)

In [17]:
import pandas as pd
import numpy as np

input_file = df   # change to your file name
output_file_cl = "output class.xlsx"


# function to collect weights from each row
def collect_weights(row):
    weights = []
    for col in df.columns:
        if col.startswith("Class"):
            val = row[col]
            if pd.notna(val):
                weights.append(val)
    return weights

# create list of weights per row
df["all_Class"] = df.apply(collect_weights, axis=1)

# group by shipmentID and combine lists
grouped_cl = df.groupby("Lane")["all_Class"].sum().reset_index()

# find max number of weights in any shipment
max_len = grouped_cl["all_Class"].apply(len).max()

# expand into separate columns
for i in range(max_len):
    grouped_cl[f"class_{i+1}"] = grouped_cl["all_Class"].apply(
        lambda x: x[i] if i < len(x) else np.nan
    )

# drop helper column
grouped_cl = grouped_cl.drop(columns=["all_Class"])

# save to Excel
grouped_cl.to_excel(output_file_cl, index=False)

In [18]:
grouped_cl

                                   Lane
0     ALLENTOWN, PA - WEST HARTFORD, CT
1          ARCADIA, FL - MOUNT AIRY, NC
2    ARROYO GRANDE, CA - SANTA CRUZ, CA
3            ATHENS, AL - HEMPSTEAD, NY
4     ATTLEBORO, MA - WEST HARTFORD, CT
..                                  ...
460     WICHITA, KS - WEST HARTFORD, CT
461      WILMINGTON, MA - LANCASTER, SC
462     WINDSOR, CT - WEST HARTFORD, CT
463   WORCESTER, MA - WEST HARTFORD, CT
464    YORKTOWN, VA - WEST HARTFORD, CT

[465 rows x 1 columns]

In [19]:
grouped_wgt.Lane.value_counts()

Lane
ALLENTOWN, PA - WEST HARTFORD, CT       1
WEST HARTFORD, CT - LEANDER, TX         1
WEST HARTFORD, CT - MAKAT CITY, PH      1
WEST HARTFORD, CT - MADISON, AL         1
WEST HARTFORD, CT - LYNCHBURG, VA       1
                                       ..
VERNON, FL - GEORGETOWN, TX             1
UNIVERSITY CENTER, MI - GRINNELL, IA    1
TYRONE, PA - WEST HARTFORD, CT          1
TRUSSVILLE, AL - WEST HARTFORD, CT      1
YORKTOWN, VA - WEST HARTFORD, CT        1
Name: count, Length: 465, dtype: int64

In [20]:
grouped_wgt = grouped_wgt.iloc[:, :9]

grouped_cl = grouped_cl.iloc[:, :9]

In [21]:
df_out = grouped_wgt.merge(grouped_cl, on='Lane')

In [22]:
df_out

                                   Lane
0     ALLENTOWN, PA - WEST HARTFORD, CT
1          ARCADIA, FL - MOUNT AIRY, NC
2    ARROYO GRANDE, CA - SANTA CRUZ, CA
3            ATHENS, AL - HEMPSTEAD, NY
4     ATTLEBORO, MA - WEST HARTFORD, CT
..                                  ...
460     WICHITA, KS - WEST HARTFORD, CT
461      WILMINGTON, MA - LANCASTER, SC
462     WINDSOR, CT - WEST HARTFORD, CT
463   WORCESTER, MA - WEST HARTFORD, CT
464    YORKTOWN, VA - WEST HARTFORD, CT

[465 rows x 1 columns]

In [23]:
df_out.to_excel('5.7.xlsx')

In [24]:
#import SMC template file to paste data into correct columns

df3 = pd.read_csv(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\SMC\SMC_Input File_template.csv')

In [26]:
df_out

                                   Lane
0     ALLENTOWN, PA - WEST HARTFORD, CT
1          ARCADIA, FL - MOUNT AIRY, NC
2    ARROYO GRANDE, CA - SANTA CRUZ, CA
3            ATHENS, AL - HEMPSTEAD, NY
4     ATTLEBORO, MA - WEST HARTFORD, CT
..                                  ...
460     WICHITA, KS - WEST HARTFORD, CT
461      WILMINGTON, MA - LANCASTER, SC
462     WINDSOR, CT - WEST HARTFORD, CT
463   WORCESTER, MA - WEST HARTFORD, CT
464    YORKTOWN, VA - WEST HARTFORD, CT

[465 rows x 1 columns]

,shipmentID,pickupDate,originCity,originStateProvince,originPostalCode,originCountry,destinationCity,destinationStateProvince,destinationPostalCode,destinationCountry,...,width7,height7,classification8,weight8,description8,packagingType8,pieces8,length8,width8,height8
0,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
1,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
2,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
4,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3193,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3194,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3195,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3196,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3197,NaN,20260429,NaN,NaN,NaN,USA,NaN,NaN,NaN,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN