In [28]:
import pandas as pd

import numpy as np

import glob

import os

In [29]:
#read in chunk folder fns

list_of_files = glob.glob(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\SMC\*.csv') # * means all if need specific format then *.csv
latest_file_edg = max(list_of_files, key=os.path.getmtime)
print(latest_file_edg)

C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\SMC\SMC_Input File_TE_Conn.csv

In [30]:
df = pd.read_csv(latest_file_edg)

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_9200\3195239348.py:1: DtypeWarning: Columns (4,21,22,29,37,38,45,46,53,54,61,62,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(latest_file_edg)

In [31]:
length = len(df)

In [32]:
length

14588

In [33]:
df

,shipmentID,pickupDate,originCity,originStateProvince,originPostalCode,originCountry,destinationCity,destinationStateProvince,destinationPostalCode,destinationCountry,...,width7,height7,classification8,weight8,description8,packagingType8,pieces8,length8,width8,height8
0,1,20260512,NaN,NaN,35020,USA,NaN,NaN,35660,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
1,2,20260512,NaN,NaN,35601,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
2,3,20260512,NaN,NaN,35758,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3,4,20260512,NaN,NaN,35811,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
4,5,20260512,NaN,NaN,35824,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14583,14584,20260512,NaN,NaN,98439,USA,NaN,NaN,94063,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14584,14585,20260512,NaN,NaN,99301,USA,NaN,NaN,79927,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14585,14586,20260512,NaN,NaN,15238,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14586,14587,20260512,NaN,NaN,11788,USA,NaN,NaN,28704,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14587,14588,20260512,NaN,NaN,38115,USA,NaN,NaN,17055,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['Origin Zip'] = df['Origin Zip'].apply(str)

df['Dest Zip'] = df['Dest Zip'].apply(str)

KeyError: 'Origin Zip'

In [34]:
df['originPostalCode']=df['originPostalCode'].apply(str)

df['destinationPostalCode']=df['destinationPostalCode'].apply(str)

In [28]:
df['Dest Zip'].dtypes

dtype('O')

In [29]:
df['Origin Zip'] = df['Origin Zip'].str.zfill(5)

df['Dest Zip'] = df['Dest Zip'].str.zfill(5)

In [35]:
df['originPostalCode']=df['originPostalCode'].str.zfill(5)

df['destinationPostalCode']=df['destinationPostalCode'].str.zfill(5)

In [36]:
df.head(60)

,shipmentID,pickupDate,originCity,originStateProvince,originPostalCode,originCountry,destinationCity,destinationStateProvince,destinationPostalCode,destinationCountry,...,width7,height7,classification8,weight8,description8,packagingType8,pieces8,length8,width8,height8
0,1,20260512,NaN,NaN,35020,USA,NaN,NaN,35660,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
1,2,20260512,NaN,NaN,35601,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
2,3,20260512,NaN,NaN,35758,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3,4,20260512,NaN,NaN,35811,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
4,5,20260512,NaN,NaN,35824,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
5,6,20260512,NaN,NaN,35824,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
6,7,20260512,NaN,NaN,35601,USA,NaN,NaN,94538,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
7,8,20260512,NaN,NaN,35601,USA,NaN,NaN,94538,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
8,9,20260512,NaN,NaN,35601,USA,NaN,NaN,94538,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
9,10,20260512,NaN,NaN,35758,USA,NaN,NaN,92154,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
10,11,20260512,NaN,NaN,35758,USA,NaN,NaN,92154,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
11,12,20260512,NaN,NaN,35007,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
12,13,20260512,NaN,NaN,35661,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
13,14,20260512,NaN,NaN,35811,USA,NaN,NaN,27409,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
14,15,20260512,NaN,NaN,35824,USA,NaN,NaN,27101,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
15,16,20260512,NaN,NaN,35824,USA,NaN,NaN,28704,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
16,17,20260512,NaN,NaN,35824,USA,NaN,NaN,28704,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
17,18,20260512,NaN,NaN,35601,USA,NaN,NaN,97070,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
18,19,20260512,NaN,NaN,35601,USA,NaN,NaN,97070,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
19,20,20260512,NaN,NaN,35601,USA,NaN,NaN,97070,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
20,21,20260512,NaN,NaN,35601,USA,NaN,NaN,97070,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
21,22,20260512,NaN,NaN,35022,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
22,23,20260512,NaN,NaN,35022,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
23,24,20260512,NaN,NaN,35022,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
24,25,20260512,NaN,NaN,35022,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
25,26,20260512,NaN,NaN,35022,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
26,27,20260512,NaN,NaN,35811,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
27,28,20260512,NaN,NaN,36105,USA,NaN,NaN,79936,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
28,29,20260512,NaN,NaN,71635,USA,NaN,NaN,85128,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
29,30,20260512,NaN,NaN,72002,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
30,31,20260512,NaN,NaN,72204,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
31,32,20260512,NaN,NaN,72442,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
32,33,20260512,NaN,NaN,71635,USA,NaN,NaN,62628,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
33,34,20260512,NaN,NaN,72015,USA,NaN,NaN,01757,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
34,35,20260512,NaN,NaN,71635,USA,NaN,NaN,39046,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
35,36,20260512,NaN,NaN,72015,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
36,37,20260512,NaN,NaN,72015,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
37,38,20260512,NaN,NaN,72015,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
38,39,20260512,NaN,NaN,72015,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
39,40,20260512,NaN,NaN,72015,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
40,41,20260512,NaN,NaN,72015,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
41,42,20260512,NaN,NaN,72114,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
42,43,20260512,NaN,NaN,72206,USA,NaN,NaN,27526,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
43,44,20260512,NaN,NaN,72442,USA,NaN,NaN,27409,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
44,45,20260512,NaN,NaN,71635,USA,NaN,NaN,43358,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
45,46,20260512,NaN,NaN,71635,USA,NaN,NaN,78870,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
46,47,20260512,NaN,NaN,85621,USA,NaN,NaN,36535,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
47,48,20260512,NaN,NaN,85621,USA,NaN,NaN,36752,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
48,49,20260512,NaN,NaN,85621,USA,NaN,NaN,72160,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
49,50,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
50,51,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
51,52,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
52,53,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
53,54,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
54,55,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
55,56,20260512,NaN,NaN,85009,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
56,57,20260512,NaN,NaN,85024,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
57,58,20260512,NaN,NaN,85027,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
58,59,20260512,NaN,NaN,85034,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
59,60,20260512,NaN,NaN,85034,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN

In [37]:
#of chunks is denominator

chnk_sz = length/3

In [38]:
chnk_sz = round(chnk_sz)

In [39]:
chnk_sz

4863

In [42]:
chnk1 = df.loc[:chnk_sz]

In [43]:
chnk1

,shipmentID,pickupDate,originCity,originStateProvince,originPostalCode,originCountry,destinationCity,destinationStateProvince,destinationPostalCode,destinationCountry,...,width7,height7,classification8,weight8,description8,packagingType8,pieces8,length8,width8,height8
0,1,20260512,NaN,NaN,35020,USA,NaN,NaN,35660,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
1,2,20260512,NaN,NaN,35601,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
2,3,20260512,NaN,NaN,35758,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
3,4,20260512,NaN,NaN,35811,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
4,5,20260512,NaN,NaN,35824,USA,NaN,NaN,85747,USA,...,NaN,NaN,NaN,NaN,Umbrellas,PAT,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4859,4860,20260512,NaN,NaN,27526,USA,NaN,NaN,19382,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4860,4861,20260512,NaN,NaN,27526,USA,NaN,NaN,19382,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4861,4862,20260512,NaN,NaN,27526,USA,NaN,NaN,19382,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4862,4863,20260512,NaN,NaN,27529,USA,NaN,NaN,17268,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4863,4864,20260512,NaN,NaN,27596,USA,NaN,NaN,17268,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
chnk2 = df.loc[chnk_sz+1:chnk_sz*2]

In [46]:
chnk_sz_3 = (chnk_sz*2)+1

In [47]:
chnk2

,shipmentID,pickupDate,originCity,originStateProvince,originPostalCode,originCountry,destinationCity,destinationStateProvince,destinationPostalCode,destinationCountry,...,width7,height7,classification8,weight8,description8,packagingType8,pieces8,length8,width8,height8
4864,4865,20260512,NaN,NaN,27617,USA,NaN,NaN,17055,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4865,4866,20260512,NaN,NaN,27804,USA,NaN,NaN,17055,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4866,4867,20260512,NaN,NaN,28152,USA,NaN,NaN,17038,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4867,4868,20260512,NaN,NaN,28152,USA,NaN,NaN,17538,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4868,4869,20260512,NaN,NaN,28269,USA,NaN,NaN,17057,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9722,9723,20260512,NaN,NaN,79936,USA,NaN,NaN,13662,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9723,9724,20260512,NaN,NaN,79936,USA,NaN,NaN,14214,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9724,9725,20260512,NaN,NaN,79936,USA,NaN,NaN,14214,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9725,9726,20260512,NaN,NaN,79936,USA,NaN,NaN,14214,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9726,9727,20260512,NaN,NaN,79936,USA,NaN,NaN,14214,USA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
chnk3 = df.loc[chnk_sz_3:chnk_sz*3]

In [49]:
chnk_sz_4 = (chnk_sz*3)+1

chnk_sz_5 = (chnk_sz*4)+1

chnk_sz_6 = (chnk_sz*5)+1

chnk_sz_7 = (chnk_sz*6)+1

chnk_sz_8 = (chnk_sz*7)+1

chnk_sz_9 = (chnk_sz*8)+1

chnk_sz_10 = (chnk_sz*9)+1

chnk_sz_11 = (chnk_sz*10)+1

chnk_sz_12 = (chnk_sz*11)+1

chnk_sz_13 = (chnk_sz*12)+1

chnk_sz_14 = (chnk_sz*13)+1

chnk_sz_15 = (chnk_sz*14)+1

In [19]:
chnk4 = df.loc[chnk_sz_4:chnk_sz*4]

chnk5 = df.loc[chnk_sz_5:chnk_sz*5]

chnk6= df.loc[chnk_sz_6:chnk_sz*6]

chnk7= df.loc[chnk_sz_7:chnk_sz*7]

chnk8= df.loc[chnk_sz_8:chnk_sz*8]

chnk9= df.loc[chnk_sz_9:chnk_sz*9]

chnk10= df.loc[chnk_sz_10:chnk_sz*10]

chnk11= df.loc[chnk_sz_11:chnk_sz*11]

chnk12= df.loc[chnk_sz_12:chnk_sz*12]

chnk13= df.loc[chnk_sz_13:chnk_sz*13]

chnk14= df.loc[chnk_sz_14:chnk_sz*14]

chnk15= df.loc[chnk_sz_15:chnk_sz*15]

In [51]:
chnk1.to_csv(r'..\comb_fl\TEC_1.csv',index=False)

chnk2.to_csv(r'..\comb_fl\TEC_2.csv',index=False)

chnk3.to_csv(r'..\comb_fl\TEC_3.csv',index=False)

#chnk4.to_excel(r'..\comb_fl\827_2_4.xls',sheet_name='Shipment_Edge', engine='openpyxl',index=False)

#chnk5.to_excel(r'..\comb_fl\824_5.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk6.to_excel(r'..\comb_fl\824_6.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk7.to_excel(r'..\comb_fl\785_7.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk8.to_excel(r'..\comb_fl\785_85.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

In [50]:
chnk1.to_csv(r'..\comb_fl\TEC_1.csv',sheet_name='Shipment_Edge', engine='openpyxl',index=False)

chnk2.to_csv(r'..\comb_fl\TEC_2.csv',sheet_name='Shipment_Edge', engine='openpyxl',index=False)

chnk3.to_csv(r'..\comb_fl\TEC_3.csv',sheet_name='Shipment_Edge', engine='openpyxl',index=False)

#chnk4.to_excel(r'..\comb_fl\827_2_4.xls',sheet_name='Shipment_Edge', engine='openpyxl',index=False)

#chnk5.to_excel(r'..\comb_fl\824_5.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk6.to_excel(r'..\comb_fl\824_6.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk7.to_excel(r'..\comb_fl\785_7.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk8.to_excel(r'..\comb_fl\785_85.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

TypeError: NDFrame.to_csv() got an unexpected keyword argument 'sheet_name'

In [73]:
#chnk9.to_excel(r'..\comb_fl\785_9.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk10.to_excel(r'..\comb_fl\785_10.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

#chnk11.to_excel(r'..\comb_fl\785_11.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

chnk12.to_excel(r'..\comb_fl\785_12.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

chnk13.to_excel(r'..\comb_fl\785_13.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

chnk14.to_excel(r'..\comb_fl\785_14.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

chnk15.to_excel(r'..\comb_fl\785_15.xls',sheet_name='Shipment_Edge',engine='openpyxl',index=False)

In [ ]:
chnk2.to_excel(r'comb_fl\joann2.xlsx',index=False)

In [ ]:
chnk2.to_excel(r'comb_fl\joann2.xlsx',index=False)

In [ ]:
chnk2.to_excel(r'comb_fl\joann2.xlsx',index=False)

In [ ]:
chnk5.to_excel(r'edge\GPI5.xlsx',index=False)

chnk6.to_excel(r'edge\GPI6.xlsx',index=False)

chnk7.to_excel(r'edge\GPI7.xlsx',index=False)

chnk8.to_excel(r'edge\GPI8.xlsx',index=False)

chnk9.to_excel(r'edge\GPI9.xlsx',index=False)

chnk10.to_excel(r'edge\GPI10.xlsx',index=False)

In [ ]:
chnk5.to_excel("comb_fl\chunkedfile5.xlsx",index=False)

In [ ]:
#df = np.array_split(df, 5)

# combining edge extracts

In [ ]:
import xlwings as xw

In [ ]:
wb = xw.Book('comb_fl\Broan1.xlsx')

wb2 = xw.Book('edge\edge template.xls')

In [ ]:
first_sheet_end = wb.sheets[0].range('A1').end('down').row

In [ ]:
first_sheet_end = str(first_sheet_end)

In [ ]:
copypr = wb.sheets[0].range('A2:'+ 'A' + first_sheet_end)

copywgt = wb.sheets[0].range('B2:'+ 'B' + first_sheet_end)

copycl = wb.sheets[0].range('C2:'+ 'C' + first_sheet_end)

copyor = wb.sheets[0].range('I2:'+ 'I' + first_sheet_end)

copydest = wb.sheets[0].range('J2:'+ 'J' + first_sheet_end)

copyplt = wb.sheets[0].range('F2:'+ 'F' + first_sheet_end)

In [ ]:
ltl_end = wb2.sheets[0].range('D1').end('down').row

In [ ]:
ltl_end

In [ ]:
copypr.copy()

wb2.sheets[0].range("A2").paste(paste='values')


copywgt.copy()

wb2.sheets[0].range("B2").paste(paste='values')