In [1]:
import pandas as pd
import numpy as np
import os

In [2]:

csv = pd.read_excel('Zip Code list (NTG LTL Quote)_Kelly Dawson.xlsx')

df = pd.DataFrame(csv)

In [3]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,TX,LTL Rate (NTG),NaN,LA,LTL Rate (NTG),NaN,OK,LTL Rate (NTG)
1,NaN,Abilene,NaN,NaN,Abbeville,NaN,NaN,Altus,NaN
2,NaN,79606,NaN,NaN,70510,NaN,NaN,73521,NaN
3,NaN,79605,NaN,NaN,Alexandria,NaN,NaN,Broken Arrow,NaN
4,NaN,79601,NaN,NaN,71303,NaN,NaN,74012,NaN
...,...,...,...,...,...,...,...,...,...
354,NaN,78746,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,NaN,Wimberley,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,NaN,78676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,NaN,Woodway,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,NaN,76712,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.rename(columns=df.iloc[0], inplace = True)

In [5]:
df

,NaN,TX,LTL Rate (NTG),NaN,LA,LTL Rate (NTG),NaN,OK,LTL Rate (NTG)
0,NaN,TX,LTL Rate (NTG),NaN,LA,LTL Rate (NTG),NaN,OK,LTL Rate (NTG)
1,NaN,Abilene,NaN,NaN,Abbeville,NaN,NaN,Altus,NaN
2,NaN,79606,NaN,NaN,70510,NaN,NaN,73521,NaN
3,NaN,79605,NaN,NaN,Alexandria,NaN,NaN,Broken Arrow,NaN
4,NaN,79601,NaN,NaN,71303,NaN,NaN,74012,NaN
...,...,...,...,...,...,...,...,...,...
354,NaN,78746,NaN,NaN,NaN,NaN,NaN,NaN,NaN
355,NaN,Wimberley,NaN,NaN,NaN,NaN,NaN,NaN,NaN
356,NaN,78676,NaN,NaN,NaN,NaN,NaN,NaN,NaN
357,NaN,Woodway,NaN,NaN,NaN,NaN,NaN,NaN,NaN
358,NaN,76712,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.dropna(axis=1, how='all')

,TX,LTL Rate (NTG),LA,LTL Rate (NTG),OK,LTL Rate (NTG)
0,TX,LTL Rate (NTG),LA,LTL Rate (NTG),OK,LTL Rate (NTG)
1,Abilene,NaN,Abbeville,NaN,Altus,NaN
2,79606,NaN,70510,NaN,73521,NaN
3,79605,NaN,Alexandria,NaN,Broken Arrow,NaN
4,79601,NaN,71303,NaN,74012,NaN
...,...,...,...,...,...,...
354,78746,NaN,NaN,NaN,NaN,NaN
355,Wimberley,NaN,NaN,NaN,NaN,NaN
356,78676,NaN,NaN,NaN,NaN,NaN
357,Woodway,NaN,NaN,NaN,NaN,NaN
358,76712,NaN,NaN,NaN,NaN,NaN

In [7]:
df = df.apply(pd.to_numeric,errors='coerce')

In [10]:
df = df.dropna(axis=0,how='all')

In [22]:
df = df.dropna(axis=1,how='all')

In [32]:
df

          TX       LA       OK
2    79606.0  70510.0  73521.0
3    79605.0      NaN      NaN
4    79601.0  71303.0  74012.0
5        NaN  71302.0      NaN
6    78516.0      NaN  73703.0
..       ...      ...      ...
350  76086.0      NaN      NaN
352  78599.0      NaN      NaN
354  78746.0      NaN      NaN
356  78676.0      NaN      NaN
358  76712.0      NaN      NaN

[243 rows x 3 columns]

In [26]:
pt_1 = df.iloc[:,0]

pt_2 = df.iloc[:,1]

pt_3 = df.iloc[:,2]

2      73521.0
3          NaN
4      74012.0
5          NaN
6      73703.0
        ...
350        NaN
352        NaN
354        NaN
356        NaN
358        NaN
Name: OK, Length: 243, dtype: float64

In [30]:
new_df = pd.concat([pt_1, pt_2, pt_3])

In [33]:
clean = pd.DataFrame(new_df)

In [37]:
clean = clean.dropna(how='any')

In [38]:
clean.to_csv('cleanzips.csv')