In [1]:
import pandas as pd

import numpy as np

import os

# Load edge output file and original file into Pandas custom folder on desktop

In [2]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas Custom')

['ADT Logistics LTL QUOTE Shipping Monday 06-24_Andrew Bond.xlsx',
 'AJWW - Walmart DCs_Erick Serratos.xlsx',
 'boydlc.xlsx',
 'boyd_lcmerge.xlsx',
 'Brookline LTL RFQ Document_Cooper Brunk - Copy.xlsx',
 'Brunk_merge.xlsx',
 'cb2.xlsx',
 'cb3.xlsx',
 'cb4.xlsx',
 'cb5.xlsx',
 'cb6.xlsx',
 'cb7.xlsx',
 'concatfl.xlsx',
 'fedextest.xlsx',
 'fezips.xlsx',
 'High Cost P & D Area Surcharge Tariff.xlsx',
 'LC chart serratos.xlsx',
 'LC chart slater.xlsx',
 'New FXNL Alt rate.xls',
 'ODFLcb.xlsx',
 'Rating_ReportCBxls.xls',
 'Rating_Report_2024_07_03_11_31_54.xls',
 'Rating_Report_boyd.xls',
 'Rating_Report_eSerratos.xls',
 'Rating_Report_fedextest.xls',
 'Rating_Report_Fedex_New.xls',
 'Rating_Report_Fedex_test new.xls',
 'Rating_Report_slater.xls',
 'report1718893897692.xls',
 'Serratos_merge.xlsx',
 'Trey_-_Rory_Whole_Foods_Updated_Eric Slater.xlsx']

In [3]:
df= pd.read_excel(r'Pandas Custom\report1718893897692.xls')

In [4]:
#df['PR'] = df['Pr'].values

In [5]:
df1 = pd.read_excel(r'Pandas Custom\Rating_Report_Fedex_test new.xls')

In [6]:
#df.rename(columns=df.iloc[8], inplace=True)

In [7]:
df1.head(10)

,OID,Primary Reference,Type,Lane ID,Carrier Name,Carrier SCAC,Contract Name,Contract Mode,Contract Service,Service Days,...,Total,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary
0,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FP FXFE LTL MG,LTL,Standard,3,...,590.82,590.82,3928.60,0.0,0.0,-3492.53,134.75,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
1,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL MG,LTL,Standard,6,...,525.20,525.20,3476.92,0.0,0.0,-3090.98,119.26,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
2,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FXFE test,LTL,Standard,3,...,590.82,590.82,3928.60,0.0,0.0,-3492.53,134.75,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
3,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FXNL test,LTL,Standard,6,...,525.20,525.20,3476.92,0.0,0.0,-3090.98,119.26,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
4,NaN,FPX00208673,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FP FXFE LTL MG,LTL,Standard,1,...,352.22,352.22,1891.89,0.0,0.0,-1668.65,68.98,60,0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...
5,NaN,FPX00208673,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL MG,LTL,Standard,2,...,340.13,340.13,1813.57,0.0,0.0,-1599.57,66.13,60,0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...
6,NaN,FPX00208673,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FXFE test,LTL,Standard,1,...,334.64,334.64,1891.89,0.0,0.0,-1682.08,64.83,60,0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...
7,NaN,FPX00208673,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FXNL test,LTL,Standard,2,...,323.27,323.27,1813.57,0.0,0.0,-1612.45,62.15,60,0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...
8,NaN,FPX00208432,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FP FXFE LTL MG,LTL,Standard,3,...,1177.13,1177.13,11333.09,0.0,0.0,-10449.11,273.15,20,0,CLEAN AIR RESOURCES BOARD FEE (AUTO APPLY) (CA...
9,NaN,FPX00208432,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL MG,LTL,Standard,5,...,1084.31,1084.31,10423.93,0.0,0.0,-9610.86,251.24,20,0,CLEAN AIR RESOURCES BOARD FEE (AUTO APPLY) (CA...

In [8]:
df

,Carrier,BOL#,Origin Zip Code,Destination Zip Code,Unnamed: 4,Total Weight,Freight Class,Total Freight Cost
0,Sutton Transport,FPX00206090,62832.0,55352,55352,2100.0,60.0,164.76
1,Frontline Freight Carrier USA,FPX00203399,90221.0,22304,22304,867.0,175.0,507.44
2,Frontline Freight Carrier USA,FPX00205119,90670.0,98661,98661,757.0,300.0,500.63
3,FedEx Economy,FPX00206281,18014.0,33312,33312,1440.0,150.0,1126.09
4,Ward,FPX00206795,19456.0,02888,02888,672.0,77.5,183.99
...,...,...,...,...,...,...,...,...
260,LTL Shipments by Carrier,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,"Copyright (c) 2000-2024 salesforce.com, inc. A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,Confidential Information - Do Not Distribute,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Generated By: Jill Damron 6/20/2024 9:31 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,FreightPros,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df['PR'] = df['BOL#'].values

In [10]:
df

,Carrier,BOL#,Origin Zip Code,Destination Zip Code,Unnamed: 4,Total Weight,Freight Class,Total Freight Cost,PR
0,Sutton Transport,FPX00206090,62832.0,55352,55352,2100.0,60.0,164.76,FPX00206090
1,Frontline Freight Carrier USA,FPX00203399,90221.0,22304,22304,867.0,175.0,507.44,FPX00203399
2,Frontline Freight Carrier USA,FPX00205119,90670.0,98661,98661,757.0,300.0,500.63,FPX00205119
3,FedEx Economy,FPX00206281,18014.0,33312,33312,1440.0,150.0,1126.09,FPX00206281
4,Ward,FPX00206795,19456.0,02888,02888,672.0,77.5,183.99,FPX00206795
...,...,...,...,...,...,...,...,...,...
260,LTL Shipments by Carrier,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,"Copyright (c) 2000-2024 salesforce.com, inc. A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,Confidential Information - Do Not Distribute,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Generated By: Jill Damron 6/20/2024 9:31 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,FreightPros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#df=df.iloc[9:]

In [12]:
df1

,OID,Primary Reference,Type,Lane ID,Carrier Name,Carrier SCAC,Contract Name,Contract Mode,Contract Service,Service Days,...,Total,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary
0,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FP FXFE LTL MG,LTL,Standard,3,...,590.82,590.82,3928.60,0.00,0.0,-3492.53,134.75,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
1,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL MG,LTL,Standard,6,...,525.20,525.20,3476.92,0.00,0.0,-3090.98,119.26,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
2,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FXFE test,LTL,Standard,3,...,590.82,590.82,3928.60,0.00,0.0,-3492.53,134.75,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
3,NaN,FPX00208552,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FXNL test,LTL,Standard,6,...,525.20,525.20,3476.92,0.00,0.0,-3090.98,119.26,20,0,CLEAN AIR RESOURCES BOARD DESTINATION (AUTO AP...
4,NaN,FPX00208673,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FP FXFE LTL MG,LTL,Standard,1,...,352.22,352.22,1891.89,0.00,0.0,-1668.65,68.98,60,0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,NaN,FPX00207993,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL MG,LTL,Standard,4,...,259.45,259.45,675.00,61.92,0.0,-584.55,47.08,60,0,HIGH COST PICKUP REGION SURCHARGE (AUTO APPLY)...
1030,NaN,FPX00207993,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FXFE test,LTL,Standard,2,...,215.02,215.02,704.00,40.50,0.0,-626.07,36.59,60,0,HIGH COST PICKUP REGION SURCHARGE (AUTO APPLY)...
1031,NaN,FPX00207993,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FXNL test,LTL,Standard,4,...,215.02,215.02,675.00,43.71,0.0,-600.28,36.59,60,0,HIGH COST PICKUP REGION SURCHARGE (AUTO APPLY)...
1032,NaN,FPX00207752,Carrier,NaN,FEDEX FREIGHT (PRIORITY),FXFE,FP FXFE LTL MG,LTL,Standard,1,...,666.99,666.99,4590.42,0.00,0.0,-4080.88,157.45,0,0,NaN
1033,NaN,FPX00207752,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL MG,LTL,Standard,2,...,634.09,634.09,4364.01,0.00,0.0,-3879.60,149.68,0,0,NaN

In [13]:
df1['Contract Name'].value_counts()

Contract Name
FP FXFE LTL MG    259
FP FXNL LTL MG    259
FXFE test         258
FXNL test         258
Name: count, dtype: int64

# Update SCACS for each file

In [14]:
car1 = df1[df1['Contract Name']=='FP FXFE LTL MG']

In [15]:
car2 = df1[df1['Contract Name']=='FP FXNL LTL MG']

In [16]:
car3 = df1[df1['Contract Name']=='FXFE test']

In [17]:
car4 = df1[df1['Contract Name']=='FXNL test']

In [ ]:
#car5 = df1[df1['Carrier SCAC']=='AACT']

In [ ]:
#car6 = df1[df1['Carrier SCAC']=='WARD']

In [ ]:
#car7 = df1[df1['Carrier SCAC']=='RDFS']

In [18]:
merge1 = df.merge(car1, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [ ]:
merge1['True'].value_counts()

In [19]:
mergecar2 = df.merge(car2, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [20]:
mergecar2

,Carrier,BOL#,Origin Zip Code,Destination Zip Code,Unnamed: 4,Total Weight,Freight Class,Total Freight Cost,PR,OID,...,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary,True
0,Sutton Transport,FPX00206090,62832.0,55352,55352,2100.0,60.0,164.76,FPX00206090,NaN,...,516.01,2257.71,0.00,0.00,-1955.18,93.48,120.0,0.0,PEAK SEASON SURCHARGE (AUTO-APPLY) (PEAKA)=75....,both
1,Frontline Freight Carrier USA,FPX00203399,90221.0,22304,22304,867.0,175.0,507.44,FPX00203399,NaN,...,1574.99,7515.76,0.00,1152.94,-7645.79,316.08,236.0,0.0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...,both
2,Frontline Freight Carrier USA,FPX00205119,90670.0,98661,98661,757.0,300.0,500.63,FPX00205119,NaN,...,1821.52,7078.56,0.00,0.00,-5839.81,382.77,200.0,0.0,CLEAN AIR RESOURCES BOARD FEE (AUTO APPLY) (CA...,both
3,FedEx Economy,FPX00206281,18014.0,33312,33312,1440.0,150.0,1126.09,FPX00206281,NaN,...,1138.91,6790.75,0.00,0.00,-5989.44,247.60,90.0,0.0,PEAK SEASON SURCHARGE (AUTO-APPLY) (PEAKA)=60....,both
4,Ward,FPX00206795,19456.0,02888,02888,672.0,77.5,183.99,FPX00206795,NaN,...,268.53,1157.12,2.64,0.00,-954.62,63.39,0.0,0.0,NaN,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,LTL Shipments by Carrier,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
261,"Copyright (c) 2000-2024 salesforce.com, inc. A...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
262,Confidential Information - Do Not Distribute,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
263,Generated By: Jill Damron 6/20/2024 9:31 AM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
264,FreightPros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [21]:
mergecar3 = df.merge(car3, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [22]:
mergecar4 = df.merge(car4, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [ ]:
mergecar5 = df.merge(car5, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [ ]:
mergecar6 = df.merge(car6, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [ ]:
#mergecar7 = df.merge(car7, how='left', left_on='PR', right_on='Primary Reference',indicator='True' )

In [23]:
fl1 = merge1.loc[:, merge1.columns.str.contains('PR|Carrier SCAC|Contract Name|Fuel|fuel|Normalized|Accessorial')]

fl2 = mergecar2.loc[:, mergecar2.columns.str.contains('PR|Carrier SCAC|Contract Name|Fuel|fuel|Normalized|Accessorial')]

fl3 = mergecar3.loc[:, mergecar3.columns.str.contains('PR|Carrier SCAC|Contract Name|Fuel|fuel|Normalized|Accessorial')]

fl4 = mergecar4.loc[:, mergecar4.columns.str.contains('PR|Carrier SCAC|Contract Name|Fuel|fuel|Normalized|Accessorial')]

#fl5 = mergecar5.loc[:, mergecar5.columns.str.contains('PR|Carrier SCAC|Fuel|fuel|Normalized|Accessorial')]

#fl6 = mergecar6.loc[:, mergecar6.columns.str.contains('PR|Carrier SCAC|Fuel|fuel|Normalized|Accessorial')]

#fl7 = mergecar7.loc[:, mergecar7.columns.str.contains('PR|Carrier SCAC|Fuel|fuel|Normalized|Accessorial')]

In [24]:
fl1['LH1'] = fl1['Normalized Total'] -fl1['Fuel Total'] - fl1['Accessorial Total']

fl2['LH2'] = fl2['Normalized Total'] -fl2['Fuel Total'] - fl2['Accessorial Total']

fl3['LH3'] = fl3['Normalized Total'] -fl3['Fuel Total'] - fl3['Accessorial Total']

fl4['LH4'] = fl4['Normalized Total'] -fl4['Fuel Total'] - fl4['Accessorial Total']

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\738849285.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['LH1'] = fl1['Normalized Total'] -fl1['Fuel Total'] - fl1['Accessorial Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\738849285.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl2['LH2'] = fl2['Normalized Total'] -fl2['Fuel Total'] - fl2['Accessorial Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\738849285.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl3['LH3'] = fl3['Normalized Total'] -fl3['Fuel Total'] - fl3['Accessorial Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\738849285.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl4['LH4'] = fl4['Normalized Total'] -fl4['Fuel Total'] - fl4['Accessorial Total']

In [25]:
fl1['Carrier Total 2'] = fl2['Normalized Total']
fl1['Scac 2'] =fl2['Carrier SCAC']
fl1['Contract 2'] = fl2['Contract Name']
fl1['FSC2'] =fl2['Fuel Total']
fl1['ASSC2'] =fl2['Accessorial Total']
fl1['LH2'] = fl2['LH2'].values

fl1['Carrier Total 3'] = fl3['Normalized Total']
fl1['Scac 3'] =fl3['Carrier SCAC']
fl1['Contract 3'] = fl3['Contract Name']
fl1['FSC3'] =fl3['Fuel Total']
fl1['ASSC3'] =fl3['Accessorial Total']
fl1['LH3'] = fl3['LH3'].values

fl1['Carrier Total 4'] = fl4['Normalized Total']
fl1['Scac 4'] =fl4['Carrier SCAC']
fl1['Contract 4'] = fl4['Contract Name']
fl1['FSC4'] =fl4['Fuel Total']
fl1['ASSC4'] =fl4['Accessorial Total']
fl1['LH4'] = fl4['LH4'].values

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Carrier Total 2'] = fl2['Normalized Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Scac 2'] =fl2['Carrier SCAC']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Contract 2'] = fl2['Contract Name']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['FSC2'] =fl2['Fuel Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['ASSC2'] =fl2['Accessorial Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['LH2'] = fl2['LH2'].values
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Carrier Total 3'] = fl3['Normalized Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Scac 3'] =fl3['Carrier SCAC']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Contract 3'] = fl3['Contract Name']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['FSC3'] =fl3['Fuel Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['ASSC3'] =fl3['Accessorial Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['LH3'] = fl3['LH3'].values
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Carrier Total 4'] = fl4['Normalized Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Scac 4'] =fl4['Carrier SCAC']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['Contract 4'] = fl4['Contract Name']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['FSC4'] =fl4['Fuel Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['ASSC4'] =fl4['Accessorial Total']
C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2379117926.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['LH4'] = fl4['LH4'].values

In [ ]:
fl1


fl1['Carrier Total 5'] = fl5['Normalized Total']

fl1['Scac 5'] =fl5['Carrier SCAC']


fl1['Carrier Total 6'] = fl6['Normalized Total']

fl1['Scac 6'] =fl6['Carrier SCAC']

fl1['Carrier Total 7'] = fl7['Normalized Total']

fl1['Scac 7'] =fl7['Carrier SCAC']

In [ ]:
fl1.iloc[133:138]

In [26]:
# LC 

fl1['LC'] = fl1[['Normalized Total','Carrier Total 2','Carrier Total 3', 'Carrier Total 4',]].min(axis=1)

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\577560408.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['LC'] = fl1[['Normalized Total','Carrier Total 2','Carrier Total 3', 'Carrier Total 4',]].min(axis=1)

In [27]:
#LH LC

fl1['LHLC'] = fl1[['LH1','LH2','LH3', 'LH4',]].min(axis=1)

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_13284\2163947615.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fl1['LHLC'] = fl1[['LH1','LH2','LH3', 'LH4',]].min(axis=1)

In [28]:
fl1

,PR,Carrier SCAC,Contract Name,Normalized Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary,LH1,Carrier Total 2,...,ASSC3,LH3,Carrier Total 4,Scac 4,Contract 4,FSC4,ASSC4,LH4,LC,LHLC
0,FPX00206090,FXFE,FP FXFE LTL MG,535.58,98.10,120.0,0.0,PEAK SEASON SURCHARGE (AUTO-APPLY) (PEAKA)=75....,317.48,516.01,...,45.0,283.60,398.76,FXNL,FXNL test,83.51,45.0,270.25,398.76,270.25
1,FPX00203399,FXFE,FP FXFE LTL MG,1750.49,357.51,236.0,0.0,HIGH COST DELIVERY REGION SURCHARGE (AUTO APPL...,1156.98,1574.99,...,161.0,949.11,1259.42,FXNL,FXNL test,259.29,161.0,839.13,1259.42,839.13
2,FPX00205119,FXFE,FP FXFE LTL MG,1924.74,407.14,200.0,0.0,CLEAN AIR RESOURCES BOARD FEE (AUTO APPLY) (CA...,1317.60,1821.52,...,95.0,728.82,991.93,FXNL,FXNL test,211.73,95.0,685.20,991.93,685.20
3,FPX00206281,FXFE,FP FXFE LTL MG,1230.31,269.18,90.0,0.0,PEAK SEASON SURCHARGE (AUTO-APPLY) (PEAKA)=60....,871.13,1138.91,...,30.0,871.13,1078.91,FXNL,FXNL test,247.60,30.0,801.31,1078.91,801.31
4,FPX00206795,FXFE,FP FXFE LTL MG,279.01,65.86,0.0,0.0,NaN,213.15,268.53,...,0.0,213.15,268.53,FXNL,FXNL test,63.39,0.0,205.14,268.53,205.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
fl1.to_excel(r'Pandas Custom\fedextest.xlsx')

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = fl1.PR

plt.plot(x, fl1.LH1)

plt.plot(x, fl1.LH2)

plt.plot(x, fl1.LH3)

plt.plot(x, fl1.LH4)

plt.legend()

In [ ]:
concatfl = pd.concat([fl1,fl2,fl3,fl4,fl5,fl6])

In [ ]:
concatfl.tail(60)

In [ ]:
concatfl = concatfl[['Carrier SCAC','Normalized Total']]

In [ ]:
Lc_scac_merge = fl1.merge(concatfl, how='left', left_on = 'LC', right_on='Normalized Total', indicator=True)

In [ ]:
Lc_scac_merge.iloc[133:138]

In [ ]:
Lc_scac_merge = Lc_scac_merge.drop_duplicates(subset=['PR'], keep='first')

In [ ]:
Lc_scac_merge.iloc[133:138]

In [ ]:
Lc_scac_merge.to_excel('Pandas Custom\Brunk_merge.xlsx')

# Below is for outputting files for ind. carriers

In [ ]:
fl3.to_excel('Pandas Custom\cb3.xlsx')

In [ ]:
fl4.to_excel('Pandas Custom\cb4.xlsx')

In [ ]:
fl5.to_excel('Pandas Custom\cb5.xlsx')

In [ ]:
fl6.to_excel('Pandas Custom\cb6.xlsx')

In [ ]:
fl7.to_excel('Pandas Custom\cb7.xlsx')

In [ ]:
fl3 = pd.read_excel('Edge Output Files\Rating_Report_chen_vers_3.xls')

In [ ]:
fl1

In [ ]:
fl1 = fl1.loc[:, fl1.columns.str.contains('Fuel|fuel|Normalized|Accessorial')]

In [ ]:
fl1['Linehaul'] = fl1['Normalized Total'] - fl1['Fuel Total'] - fl1['Accessorial Total']

In [ ]:
fl2['Linehaul'] = fl2['Normalized Total'] - fl2['Fuel Total'] - fl2['Accessorial Total']

In [ ]:
fl3['Linehaul'] = fl3['Normalized Total'] - fl3['Fuel Total'] - fl3['Accessorial Total']

In [ ]:
fl1.to_csv('linehaul/vers1lh.csv')

In [ ]:
fl2.to_csv('linehaul/vers2lh.csv')

In [ ]:
fl3.to_csv('linehaul/vers3lh.csv')

In [ ]:
fl1['Linehaul']