In [1]:
import pandas as pd

import numpy as np

import os
import glob

In [5]:
list_of_files = glob.glob(r'C:\Users\matthew.shuff\Downloads\*') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\Downloads\BluLinx_LTL data.xlsx

In [6]:
df = pd.read_excel(latest_file)

In [7]:
df1 = pd.read_excel('../Pandas Custom 2/ZIP_Locale_Detail (2).xls')

In [8]:
df.columns

Index(['Plan Status', 'Origin', 'Origin City', 'Origin State', 'Destination',
       'Destination City', 'Destination State', 'Distance',
       'Planned Departure Date', 'Planned Arrival End', 'Equipment', 'Weight',
       'Mode', 'Carrier', 'SCAC', 'Price', 'Carrier Ref./Conf. #',
       'Created Date', 'Description', 'Class Code', 'Quantity',
       'Pickup Appointment Date', 'Ship Month', 'Weight Num', 'Distance Num'],
      dtype='object')

In [10]:
df['Origin City'] = df['Origin City'].apply(str)

df['Origin State'] = df['Origin State'].apply(str)

df['Destination City'] = df['Destination City'].apply(str)

df['Destination State'] = df['Destination State'].apply(str)

In [11]:
df['Origin City'] = df['Origin City'].str.upper()

df['Origin State'] = df['Origin State'].str.upper()

df['Destination City'] = df['Destination City'].str.upper()

df['Destination State'] = df['Destination State'].str.upper()

In [12]:
df1.columns

Index(['AREA NAME', 'AREA CODE', 'DISTRICT NAME', 'DISTRICT NO',
       'DELIVERY ZIPCODE', 'LOCALE NAME', 'PHYSICAL DELV ADDR',
       'PHYSICAL CITY', 'PHYSICAL STATE', 'PHYSICAL ZIP', 'PHYSICAL ZIP 4'],
      dtype='object')

In [13]:
df

,Plan Status,Origin,Origin City,Origin State,Destination,Destination City,Destination State,Distance,Planned Departure Date,Planned Arrival End,...,Price,Carrier Ref./Conf. #,Created Date,Description,Class Code,Quantity,Pickup Appointment Date,Ship Month,Weight Num,Distance Num
0,Covered,BlueLinx Corporation,TAMPA,FL,"TIBBETTS-PENSACOLA, LMC 408600",PENSACOLA,FL,425 mi,15-Oct-25 12:01 AM EDT,15-Oct-25 11:59 PM CDT,...,135.91,4.467991e+08,14-Oct-25 2:26 PM EDT,1 palletized - boxes of sealant,65.0,1 ea,15-Oct-25 1:53 PM EDT,2025-10-01,702.00,425
1,Covered,"TAMLYN & SONS, INC. 20300",STAFFORD,TX,IMPORT AND EXPORT SOLUTIONS,DEERFIELD BEACH,FL,"1,155 mi",30-Jan-26 12:01 AM CST,30-Jan-26 11:59 PM EST,...,168.92,1.560724e+09,29-Jan-26 12:16 PM EST,10 ft Moulding,65.0,1 ea,30-Jan-26 1:51 PM CST,2026-01-01,10.00,1155
2,Covered,TAPCO COMPANIES,MEADVILLE,PA,BLUELINX CHICAGO,UNIVERSITY PARK,IL,420 mi,27-Jan-26 12:01 AM EST,28-Jan-26 11:59 PM CST,...,603.78,NaN,23-Jan-26 2:41 PM EST,100 in x 20 in x 24 in - jack posts,65.0,10 ea,NaN,2026-01-01,7403.00,420
3,Covered,ALL VAN,LAVERGNE,TN,BLUELINX BELLINGHAM,BELLINGHAM,MA,"1,068 mi",06-Mar-26 8:00 AM CST,10-Mar-26 5:00 PM EDT,...,172.23,3.736724e+08,05-Mar-26 3:10 PM EST,108 in x 10 x 4 - curtainside accessories - pa...,65.0,2 ea,06-Mar-26 1:15 AM CST,2026-03-01,51.00,1068
4,Covered,ROYAL MOULDING LTD-BRISTOL T2,BRISTOL,TN,GUY C LEE B/M KITTY HAWK,KITTY HAWK,NC,441 mi,24-Feb-26 12:01 AM EST,25-Feb-26 11:59 PM EST,...,326.67,3.914221e+08,20-Feb-26 9:11 AM EST,10ft - 12ft - Moulding units,65.0,2 ea,24-Feb-26 1:36 PM EST,2026-02-01,1709.06,441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,Covered,BLUELINX ATLANTA,LAWRENCEVILLE,GA,BLUELINX NASHVILLE,MADISON,TN,273 mi,13-Nov-25 12:01 AM EST,13-Nov-25 11:59 PM CST,...,166.40,4.635333e+08,10-Nov-25 10:41 AM EST,NaN,NaN,1 ea,13-Nov-25 2:16 PM EST,2025-11-01,75.00,273
226,Covered,MATEENBAR COMPOSITE,CONCORD,NC,SOUTHERN PINE LUMBER,ROCKLEDGE,FL,545 mi,11-Nov-25 12:01 AM EST,11-Nov-25 11:59 PM EST,...,166.40,4.614350e+08,10-Nov-25 3:26 PM EST,NaN,NaN,1 ea,11-Nov-25 3:28 PM EST,2025-11-01,200.00,545
227,Covered,BlueLinx Corporation,TAMPA,FL,SkyTown Site C,ST PETERSBURG,FL,21 mi,10-Dec-25 12:01 AM EST,12-Dec-25 11:59 PM EST,...,108.94,NaN,02-Dec-25 11:56 AM EST,NaN,NaN,0 ea,NaN,2025-12-01,25.00,21
228,Covered,RSG,NORTH WILKESBORO,NC,BLUELINX ATLANTA,LAWRENCEVILLE,GA,293 mi,09-Jan-26 12:01 AM EST,12-Jan-26 11:59 PM EST,...,165.20,4.521161e+08,30-Dec-25 3:16 PM EST,NaN,NaN,0 ea,09-Jan-26 4:46 PM EST,2026-01-01,1944.00,293
229,Covered,BLUELINX TAMPA,TAMPA,FL,BLUELINX PENSACOLA,PENSACOLA,FL,425 mi,17-Mar-26 12:01 AM EDT,20-Mar-26 11:59 PM CDT,...,112.61,4.779646e+08,16-Mar-26 4:06 PM EDT,NaN,NaN,0 ea,17-Mar-26 8:46 AM EDT,2026-03-01,104.40,425

In [ ]:
df['D']= df['D'].str.strip()

df['st'] = df['st'].str.strip()

In [14]:
df1 = df1.drop_duplicates(['PHYSICAL CITY','PHYSICAL STATE'])

In [15]:
df2 = pd.merge(df,df1, left_on=['Origin City','Origin State'], right_on=['PHYSICAL CITY', 'PHYSICAL STATE'], how='left', indicator=True)

In [ ]:
#df3 = df2.merge(df1,left_on=['Consignee\nCity','Consignee\nState'], right_on=['PHYSICAL CITY', 'PHYSICAL STATE'], how='left', indicator='merge2')

In [16]:
df2

,Plan Status,Origin,Origin City,Origin State,Destination,Destination City,Destination State,Distance,Planned Departure Date,Planned Arrival End,...,DISTRICT NAME,DISTRICT NO,DELIVERY ZIPCODE,LOCALE NAME,PHYSICAL DELV ADDR,PHYSICAL CITY,PHYSICAL STATE,PHYSICAL ZIP,PHYSICAL ZIP 4,_merge
0,Covered,BlueLinx Corporation,TAMPA,FL,"TIBBETTS-PENSACOLA, LMC 408600",PENSACOLA,FL,425 mi,15-Oct-25 12:01 AM EDT,15-Oct-25 11:59 PM CDT,...,FLORIDA 2,335.0,33601.0,COMMERCE,401 N ASHLEY DR,TAMPA,FL,33602.0,4301.0,both
1,Covered,"TAMLYN & SONS, INC. 20300",STAFFORD,TX,IMPORT AND EXPORT SOLUTIONS,DEERFIELD BEACH,FL,"1,155 mi",30-Jan-26 12:01 AM CST,30-Jan-26 11:59 PM EST,...,TEXAS 2,770.0,77477.0,STAFFORD,4110 BLUEBONNET DR,STAFFORD,TX,77477.0,9998.0,both
2,Covered,TAPCO COMPANIES,MEADVILLE,PA,BLUELINX CHICAGO,UNIVERSITY PARK,IL,420 mi,27-Jan-26 12:01 AM EST,28-Jan-26 11:59 PM CST,...,PENNSYLVANIA 1,150.0,16335.0,MEADVILLE,212 ARCH ST,MEADVILLE,PA,16335.0,3400.0,both
3,Covered,ALL VAN,LAVERGNE,TN,BLUELINX BELLINGHAM,BELLINGHAM,MA,"1,068 mi",06-Mar-26 8:00 AM CST,10-Mar-26 5:00 PM EDT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,Covered,ROYAL MOULDING LTD-BRISTOL T2,BRISTOL,TN,GUY C LEE B/M KITTY HAWK,KITTY HAWK,NC,441 mi,24-Feb-26 12:01 AM EST,25-Feb-26 11:59 PM EST,...,VIRGINIA,230.0,37625.0,VOLUNTEER,1430 VOLUNTEER PKWY STE 32,BRISTOL,TN,37620.0,9997.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,Covered,BLUELINX ATLANTA,LAWRENCEVILLE,GA,BLUELINX NASHVILLE,MADISON,TN,273 mi,13-Nov-25 12:01 AM EST,13-Nov-25 11:59 PM CST,...,GEORGIA,300.0,30042.0,LAWRENCEVILLE,35 PATTERSON RD,LAWRENCEVILLE,GA,30044.0,4717.0,both
226,Covered,MATEENBAR COMPOSITE,CONCORD,NC,SOUTHERN PINE LUMBER,ROCKLEDGE,FL,545 mi,11-Nov-25 12:01 AM EST,11-Nov-25 11:59 PM EST,...,NORTH CAROLINA,270.0,28025.0,CONCORD,66 MCCACHERN BLVD SE,CONCORD,NC,28025.0,9998.0,both
227,Covered,BlueLinx Corporation,TAMPA,FL,SkyTown Site C,ST PETERSBURG,FL,21 mi,10-Dec-25 12:01 AM EST,12-Dec-25 11:59 PM EST,...,FLORIDA 2,335.0,33601.0,COMMERCE,401 N ASHLEY DR,TAMPA,FL,33602.0,4301.0,both
228,Covered,RSG,NORTH WILKESBORO,NC,BLUELINX ATLANTA,LAWRENCEVILLE,GA,293 mi,09-Jan-26 12:01 AM EST,12-Jan-26 11:59 PM EST,...,NORTH CAROLINA,270.0,28659.0,NORTH WILKESBORO,300 8TH ST,NORTH WILKESBORO,NC,28659.0,4163.0,both
229,Covered,BLUELINX TAMPA,TAMPA,FL,BLUELINX PENSACOLA,PENSACOLA,FL,425 mi,17-Mar-26 12:01 AM EDT,20-Mar-26 11:59 PM CDT,...,FLORIDA 2,335.0,33601.0,COMMERCE,401 N ASHLEY DR,TAMPA,FL,33602.0,4301.0,both

In [ ]:
df2.to_excel('1.16.26.xlsx')

In [19]:
df3 = pd.merge(df2,df1, left_on=['Destination City','Destination State'], right_on=['PHYSICAL CITY', 'PHYSICAL STATE'], how='left', indicator='_both')

In [20]:
df3

,Plan Status,Origin,Origin City,Origin State,Destination,Destination City,Destination State,Distance,Planned Departure Date,Planned Arrival End,...,DISTRICT NAME_y,DISTRICT NO_y,DELIVERY ZIPCODE_y,LOCALE NAME_y,PHYSICAL DELV ADDR_y,PHYSICAL CITY_y,PHYSICAL STATE_y,PHYSICAL ZIP_y,PHYSICAL ZIP 4_y,_both
0,Covered,BlueLinx Corporation,TAMPA,FL,"TIBBETTS-PENSACOLA, LMC 408600",PENSACOLA,FL,425 mi,15-Oct-25 12:01 AM EDT,15-Oct-25 11:59 PM CDT,...,FLORIDA 1,320.0,32501.0,EAST HILL,3001 N DAVIS HWY,PENSACOLA,FL,32503.0,9998.0,both
1,Covered,"TAMLYN & SONS, INC. 20300",STAFFORD,TX,IMPORT AND EXPORT SOLUTIONS,DEERFIELD BEACH,FL,"1,155 mi",30-Jan-26 12:01 AM CST,30-Jan-26 11:59 PM EST,...,FLORIDA 3,330.0,33441.0,DEERFIELD BEACH,212 E HILLSBORO BLVD,DEERFIELD BEACH,FL,33441.0,9998.0,both
2,Covered,TAPCO COMPANIES,MEADVILLE,PA,BLUELINX CHICAGO,UNIVERSITY PARK,IL,420 mi,27-Jan-26 12:01 AM EST,28-Jan-26 11:59 PM CST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,Covered,ALL VAN,LAVERGNE,TN,BLUELINX BELLINGHAM,BELLINGHAM,MA,"1,068 mi",06-Mar-26 8:00 AM CST,10-Mar-26 5:00 PM EDT,...,MA-RI,20.0,2019.0,BELLINGHAM,111 MECHANIC ST,BELLINGHAM,MA,2019.0,9998.0,both
4,Covered,ROYAL MOULDING LTD-BRISTOL T2,BRISTOL,TN,GUY C LEE B/M KITTY HAWK,KITTY HAWK,NC,441 mi,24-Feb-26 12:01 AM EST,25-Feb-26 11:59 PM EST,...,NORTH CAROLINA,270.0,27941.0,KITTY HAWK,3841 N CROATAN HWY,KITTY HAWK,NC,27949.0,9238.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,Covered,BLUELINX ATLANTA,LAWRENCEVILLE,GA,BLUELINX NASHVILLE,MADISON,TN,273 mi,13-Nov-25 12:01 AM EST,13-Nov-25 11:59 PM CST,...,TENNESSEE,370.0,37115.0,MADISON,323 E OLD HICKORY BLVD,MADISON,TN,37115.0,9998.0,both
226,Covered,MATEENBAR COMPOSITE,CONCORD,NC,SOUTHERN PINE LUMBER,ROCKLEDGE,FL,545 mi,11-Nov-25 12:01 AM EST,11-Nov-25 11:59 PM EST,...,FLORIDA 2,335.0,32955.0,ROCKLEDGE,3000 MURRELL RD,ROCKLEDGE,FL,32955.0,9998.0,both
227,Covered,BlueLinx Corporation,TAMPA,FL,SkyTown Site C,ST PETERSBURG,FL,21 mi,10-Dec-25 12:01 AM EST,12-Dec-25 11:59 PM EST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
228,Covered,RSG,NORTH WILKESBORO,NC,BLUELINX ATLANTA,LAWRENCEVILLE,GA,293 mi,09-Jan-26 12:01 AM EST,12-Jan-26 11:59 PM EST,...,GEORGIA,300.0,30042.0,LAWRENCEVILLE,35 PATTERSON RD,LAWRENCEVILLE,GA,30044.0,4717.0,both
229,Covered,BLUELINX TAMPA,TAMPA,FL,BLUELINX PENSACOLA,PENSACOLA,FL,425 mi,17-Mar-26 12:01 AM EDT,20-Mar-26 11:59 PM CDT,...,FLORIDA 1,320.0,32501.0,EAST HILL,3001 N DAVIS HWY,PENSACOLA,FL,32503.0,9998.0,both

In [22]:
df3.to_csv('4_28_2026.csv')

In [24]:
import pandas as pd
from uszipcode import SearchEngine

# Initialize zipcode search
search = SearchEngine(simple_zipcode=True)

# Load your data
df = pd.read_csv(lates_file)

# Assign columns (based on your structure)
df.columns = ["Origin_City", "Origin_State", "Customer", "Dest_City", "Dest_State"]

# Function to get primary zip
def get_zip(city, state):
    try:
        result = search.by_city_and_state(city, state)
        if result:
            return result[0].zipcode  # first (most common)
    except:
        return None
    return None

# Apply to dataframe
df["Origin"] = df.apply(lambda x: get_zip(x["Origin_City"], x["Origin_State"]), axis=1)
df["Destination"] = df.apply(lambda x: get_zip(x["Dest_City"], x["Dest_State"]), axis=1)

# Keep only needed columns
output = df[["Origin", "Destination"]]

# Save file
output.to_csv("output_with_zips.csv", index=False)

print("Done!")

ImportError: cannot import name 'SearchEngine' from 'uszipcode' (C:\Users\matthew.shuff\AppData\Local\anaconda3\Lib\site-packages\uszipcode\__init__.py)