In [1]:
import pandas as pd
import numpy as np
import os
from ast import literal_eval
import glob

In [2]:
#import most recent file in SMC output folder

list_of_files = glob.glob(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\SMC\SMC output\*.csv') # * means all if need specific format then *.csv
latest_file = max(list_of_files, key=os.path.getmtime)
print(latest_file)

C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\SMC\SMC output\TEC.csv

In [3]:
df = pd.read_csv(latest_file, skiprows=5)



#df1 = pd.read_excel(latest_file, sheet_name='Product Details')

df

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_27304\3478144305.py:1: DtypeWarning: Columns (5,22,23,30,38,39,46,47,54,55,62,63,70,71,121) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(latest_file, skiprows=5)

,rowNumber,shipmentID,pickupDate,originCity,originStateProvince,originPostalCode,originCountry,destinationCity,destinationStateProvince,destinationPostalCode,...,accessorialChargesTotal.5,transitInfo.5,errors/information.5,totalCharges.6,fuelTotal.6,accessorialCodes.7,accessorialCharges.6,accessorialChargesTotal.6,transitInfo.6,errors/information.6
0,1.0,1,20260512,NaN,NaN,35020,USA,NaN,NaN,35660,...,0,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
1,2.0,2,20260512,NaN,NaN,35601,USA,NaN,NaN,85747,...,0,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
2,3.0,3,20260512,NaN,NaN,35758,USA,NaN,NaN,85747,...,0,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
3,4.0,4,20260512,NaN,NaN,35811,USA,NaN,NaN,85747,...,0,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
4,5.0,5,20260512,NaN,NaN,35824,USA,NaN,NaN,85747,...,0,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14583,NaN,14584,20260512,NaN,NaN,98439,USA,NaN,NaN,94063,...,25,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
14584,NaN,14585,20260512,NaN,NaN,99301,USA,NaN,NaN,79927,...,0,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
14585,NaN,14586,20260512,NaN,NaN,15238,USA,NaN,NaN,85747,...,0,5 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
14586,NaN,14587,20260512,NaN,NaN,11788,USA,NaN,NaN,28704,...,0,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...
14587,NaN,14588,20260512,NaN,NaN,38115,USA,NaN,NaN,17055,...,0,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...

In [4]:
df2 = pd.read_csv(latest_file,skiprows=4)

df2 = df2.iloc[1:]

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_27304\3596305454.py:1: DtypeWarning: Columns (0,1,2,3,4,7,8,9,11,12,13,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,80,83,84,85,86,87,90,91,93,94,97,98,101,104,105,106,107,108,109,111,112,114,115,118,119,121,122) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(latest_file,skiprows=4)

In [5]:
df2['PR'] = df2['Unnamed: 1']

In [6]:
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,C1 TFIN STND.5,C1 TFIN STND.6,C1 TOTL STND,C1 TOTL STND.1,C1 TOTL STND.2,C1 TOTL STND.3,C1 TOTL STND.4,C1 TOTL STND.5,C1 TOTL STND.6,PR
1,1,1,20260512,NaN,NaN,35020,USA,NaN,NaN,35660,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,1
2,2,2,20260512,NaN,NaN,35601,USA,NaN,NaN,85747,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,2
3,3,3,20260512,NaN,NaN,35758,USA,NaN,NaN,85747,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,3
4,4,4,20260512,NaN,NaN,35811,USA,NaN,NaN,85747,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,4
5,5,5,20260512,NaN,NaN,35824,USA,NaN,NaN,85747,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14584,NaN,14584,20260512,NaN,NaN,98439,USA,NaN,NaN,94063,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14584
14585,NaN,14585,20260512,NaN,NaN,99301,USA,NaN,NaN,79927,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14585
14586,NaN,14586,20260512,NaN,NaN,15238,USA,NaN,NaN,85747,...,5 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14586
14587,NaN,14587,20260512,NaN,NaN,11788,USA,NaN,NaN,28704,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14587
14588,NaN,14588,20260512,NaN,NaN,38115,USA,NaN,NaN,17055,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14588

In [7]:
df2.columns = df2.columns.str.replace('C1','')

df2.columns = df2.columns.str.replace('STND','')

df2.columns = df2.columns.str.replace(' ','')

#df2.columns = df2.columns.str.replace('PR','') 

#df2.columns = df2.columns.remove('')

In [8]:
df2 = df2.loc[:,~df2.columns.str.contains('Unnamed')]

In [9]:
col_list_2 = df2.columns.tolist()

In [10]:
col_list_2

['AACT',
 'AACT.1',
 'AACT.2',
 'AACT.3',
 'AACT.4',
 'AACT.5',
 'AACT.6',
 'ABFS',
 'ABFS.1',
 'ABFS.2',
 'ABFS.3',
 'ABFS.4',
 'ABFS.5',
 'ABFS.6',
 'CTII',
 'CTII.1',
 'CTII.2',
 'CTII.3',
 'CTII.4',
 'CTII.5',
 'CTII.6',
 'FCSY',
 'FCSY.1',
 'FCSY.2',
 'FCSY.3',
 'FCSY.4',
 'FCSY.5',
 'FCSY.6',
 'SEFL',
 'SEFL.1',
 'SEFL.2',
 'SEFL.3',
 'SEFL.4',
 'SEFL.5',
 'SEFL.6',
 'TFIN',
 'TFIN.1',
 'TFIN.2',
 'TFIN.3',
 'TFIN.4',
 'TFIN.5',
 'TFIN.6',
 'TOTL',
 'TOTL.1',
 'TOTL.2',
 'TOTL.3',
 'TOTL.4',
 'TOTL.5',
 'TOTL.6',
 'PR']

In [11]:
car_list = df2.loc[:,~df2.columns.str.contains('1|2|3|4|5|6')]

In [12]:
fuel  = df2.loc[:,df2.columns.str.contains('1|PR')]

Assc = df2.loc[:,df2.columns.str.contains('2|PR')]

In [13]:
df_fl = car_list.merge(fuel,on='PR')

In [14]:
df_fl.to_csv('Jockey.csv')

In [14]:
car_list = car_list.loc[:,~car_list.columns.str.contains('PR')]

In [15]:
car_list = car_list.columns.tolist()

car_list

['AACT', 'ABFS', 'CTII', 'FCSY', 'SEFL', 'TFIN', 'TOTL']

In [16]:
car_list

['AACT', 'ABFS', 'CTII', 'FCSY', 'SEFL', 'TFIN', 'TOTL']

In [17]:
car_list = [col.replace(' ','') for col in car_list]

car_list = [col.replace('PR','') for col in car_list]

In [18]:
car_list

['AACT', 'ABFS', 'CTII', 'FCSY', 'SEFL', 'TFIN', 'TOTL']

In [19]:
col_list_2 = list(set(col_list_2))

col_list_2

['TOTL.6',
 'AACT',
 'CTII.6',
 'CTII.3',
 'ABFS.5',
 'TOTL',
 'ABFS.1',
 'FCSY.1',
 'TOTL.4',
 'FCSY.2',
 'FCSY.5',
 'FCSY.6',
 'AACT.2',
 'ABFS.4',
 'SEFL',
 'AACT.4',
 'SEFL.1',
 'PR',
 'AACT.3',
 'ABFS.3',
 'CTII.1',
 'ABFS.6',
 'AACT.5',
 'ABFS.2',
 'TFIN.2',
 'FCSY.4',
 'CTII',
 'AACT.6',
 'TOTL.3',
 'CTII.2',
 'TOTL.2',
 'SEFL.6',
 'ABFS',
 'TFIN.5',
 'TFIN.1',
 'CTII.4',
 'CTII.5',
 'SEFL.2',
 'SEFL.4',
 'SEFL.3',
 'FCSY.3',
 'TOTL.1',
 'AACT.1',
 'FCSY',
 'TFIN.4',
 'TFIN',
 'TOTL.5',
 'TFIN.3',
 'SEFL.5',
 'TFIN.6']

In [20]:
df2

,AACT,AACT.1,AACT.2,AACT.3,AACT.4,AACT.5,AACT.6,ABFS,ABFS.1,ABFS.2,...,TFIN.5,TFIN.6,TOTL,TOTL.1,TOTL.2,TOTL.3,TOTL.4,TOTL.5,TOTL.6,PR
1,125.01,40.77,NaN,NaN,0,1 D/D,NaN,246.65,NaN,NaN,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,1
2,1472.93,480.39,NaN,NaN,0,5 D/D,NaN,1365.29,NaN,NaN,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,2
3,176.63,57.61,NaN,NaN,0,5 D/D,NaN,395.39,NaN,NaN,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,3
4,289.2,94.32,NaN,NaN,0,5 D/D,NaN,408.87,NaN,NaN,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,4
5,1408,459.21,NaN,NaN,0,5 D/D,NaN,1138.83,NaN,NaN,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14584,249.31,73.16,CCS,25,25.0,3 D/D,NaN,312.91,NaN,NaN,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14584
14585,250.63,81.74,NaN,NaN,0.0,4 D/D,NaN,NaN,NaN,NaN,...,4 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14585
14586,NaN,NaN,NaN,NaN,0.0,NaN,10000018 No results returned.: {The request to...,479.16,NaN,NaN,...,5 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14586
14587,NaN,NaN,NaN,NaN,0.0,NaN,10000018 No results returned.: {The request to...,276.45,NaN,NaN,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14587
14588,225.23,73.46,NaN,NaN,0.0,3 D/D,NaN,265.76,NaN,NaN,...,2 D/D,NaN,NaN,NaN,NaN,NaN,0,NaN,10000402 CarrierMessage: {The pickup zip code ...,14588

In [21]:
df2 = df2.fillna(888888.00)

In [22]:
df2[car_list] = pd.DataFrame(df2[car_list])

In [23]:
df2

,AACT,AACT.1,AACT.2,AACT.3,AACT.4,AACT.5,AACT.6,ABFS,ABFS.1,ABFS.2,...,TFIN.5,TFIN.6,TOTL,TOTL.1,TOTL.2,TOTL.3,TOTL.4,TOTL.5,TOTL.6,PR
1,125.01,40.77,888888.0,888888.0,0,1 D/D,888888.0,246.65,888888.0,888888.0,...,2 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,1
2,1472.93,480.39,888888.0,888888.0,0,5 D/D,888888.0,1365.29,888888.0,888888.0,...,4 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,2
3,176.63,57.61,888888.0,888888.0,0,5 D/D,888888.0,395.39,888888.0,888888.0,...,4 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,3
4,289.2,94.32,888888.0,888888.0,0,5 D/D,888888.0,408.87,888888.0,888888.0,...,4 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,4
5,1408,459.21,888888.0,888888.0,0,5 D/D,888888.0,1138.83,888888.0,888888.0,...,4 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14584,249.31,73.16,CCS,25,25.0,3 D/D,888888.0,312.91,888888.0,888888.0,...,2 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,14584
14585,250.63,81.74,888888.0,888888.0,0.0,4 D/D,888888.0,888888.0,888888.0,888888.0,...,4 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,14585
14586,888888.0,888888.0,888888.0,888888.0,0.0,888888.0,10000018 No results returned.: {The request to...,479.16,888888.0,888888.0,...,5 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,14586
14587,888888.0,888888.0,888888.0,888888.0,0.0,888888.0,10000018 No results returned.: {The request to...,276.45,888888.0,888888.0,...,2 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,14587
14588,225.23,73.46,888888.0,888888.0,0.0,3 D/D,888888.0,265.76,888888.0,888888.0,...,2 D/D,888888.0,888888.0,888888.0,888888.0,888888.0,0,888888.0,10000402 CarrierMessage: {The pickup zip code ...,14588

In [24]:
df2_subs = df2[car_list].astype('float64')

In [25]:
df2_subs

            AACT       ABFS     CTII      FCSY      SEFL     TFIN      TOTL
1         125.01     246.65   185.39  888888.0  888888.0   209.88  888888.0
2        1472.93    1365.29  1779.35  888888.0  888888.0  1129.02  888888.0
3         176.63     395.39   164.59  888888.0  888888.0   215.55  888888.0
4         289.20     408.87   353.15  888888.0  888888.0   353.24  888888.0
5        1408.00    1138.83  1753.52  888888.0  888888.0  1068.41  888888.0
...          ...        ...      ...       ...       ...      ...       ...
14584     249.31     312.91   191.42  888888.0  888888.0   258.68  888888.0
14585     250.63  888888.00   290.29  888888.0  888888.0   297.18  888888.0
14586  888888.00     479.16   199.53  888888.0  888888.0   220.92  888888.0
14587  888888.00     276.45   128.79     295.5  888888.0   220.92  888888.0
14588     225.23     265.76   132.92  888888.0  888888.0   194.06  888888.0

[14588 rows x 7 columns]

In [26]:
df2_subs['LC'] = df2_subs.min(axis=1)

df2_subs['PR'] = df2['PR'].values

In [27]:
df2_subs

,AACT,ABFS,CTII,FCSY,SEFL,TFIN,TOTL,LC,PR
1,125.01,246.65,185.39,888888.0,888888.0,209.88,888888.0,125.01,1
2,1472.93,1365.29,1779.35,888888.0,888888.0,1129.02,888888.0,1129.02,2
3,176.63,395.39,164.59,888888.0,888888.0,215.55,888888.0,164.59,3
4,289.20,408.87,353.15,888888.0,888888.0,353.24,888888.0,289.20,4
5,1408.00,1138.83,1753.52,888888.0,888888.0,1068.41,888888.0,1068.41,5
...,...,...,...,...,...,...,...,...,...
14584,249.31,312.91,191.42,888888.0,888888.0,258.68,888888.0,191.42,14584
14585,250.63,888888.00,290.29,888888.0,888888.0,297.18,888888.0,250.63,14585
14586,888888.00,479.16,199.53,888888.0,888888.0,220.92,888888.0,199.53,14586
14587,888888.00,276.45,128.79,295.5,888888.0,220.92,888888.0,128.79,14587
14588,225.23,265.76,132.92,888888.0,888888.0,194.06,888888.0,132.92,14588

In [28]:
df = df2_subs

# Function to find matching column header
def find_matching_column(row):
    lc_value = row['LC']
    
    for col in df.columns:
        # Skip LC column itself if needed
        if col == 'LC':
            continue
        
        if row[col] == lc_value:
            return col
    
    return None  # if no match found

# Apply function to each row
df['SCAC'] = df.apply(find_matching_column, axis=1)

# Save output
df.to_csv("output_with_match.csv", index=False)

In [30]:
df2_subs.to_csv('4_24_.csv',index=False)