In [2]:
import pandas as pd

import numpy as np

import os

In [ ]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Python Outputs')

In [ ]:
df = pd.read_excel('Python Outputs\Stevens file.xlsx')

In [ ]:
df

In [ ]:
df1 = df[df['LTL 1-10 Pallets / Price Per Pallet']==1]

df2 = df[df['LTL 1-10 Pallets / Price Per Pallet']==2]

df3 = df[df['LTL 1-10 Pallets / Price Per Pallet']==3]

df4 = df[df['LTL 1-10 Pallets / Price Per Pallet']==4]

df5 = df[df['LTL 1-10 Pallets / Price Per Pallet']==5]

df6 = df[df['LTL 1-10 Pallets / Price Per Pallet']==6]

df7 = df[df['LTL 1-10 Pallets / Price Per Pallet']==7]

df8 = df[df['LTL 1-10 Pallets / Price Per Pallet']==8]

In [ ]:
df_ind = df1.index.tolist

In [ ]:
df1['P1 Rate'] = df1['P1-8']

df1['P1 SCAC'] = df1['Unnamed: 10']

In [ ]:
df2['P2 Rate'] = df2['P1-8']

df2['P2 SCAC'] = df2['Unnamed: 10']

In [ ]:
df3['P3 Rate'] = df3['P1-8']

df3['P3 SCAC'] = df3['Unnamed: 10']

In [ ]:
df4['P4 Rate'] = df4['P1-8']

df4['P4 SCAC'] = df4['Unnamed: 10']

In [ ]:
df5['P5 Rate'] = df5['P1-8']

df5['P5 SCAC'] = df5['Unnamed: 10']

In [ ]:
df6['P6 Rate'] = df6['P1-8']

df6['P6 SCAC'] = df6['Unnamed: 10']

In [ ]:
df7['P7 Rate'] = df7['P1-8']

df7['P7 SCAC'] = df7['Unnamed: 10']

In [ ]:
df8['P8 Rate'] = df8['P1-8']

df8['P8 SCAC'] = df8['Unnamed: 10']

In [ ]:
df1['P2 Rates'] = df2['P2 Rate'].values

df1['P2 SCAC'] = df2['P2 SCAC'].values

df1['P3 Rates'] = df3['P3 Rate'].values

df1['P3 SCAC'] = df3['P3 SCAC'].values

df1['P4 Rates'] = df4['P4 Rate'].values

df1['P4 SCAC'] = df4['P4 SCAC'].values

df1['P5 Rates'] = df5['P5 Rate'].values

df1['P5 SCAC'] = df5['P5 SCAC'].values

df1['P6 Rates'] = df6['P6 Rate'].values

df1['P6 SCAC'] = df6['P6 SCAC'].values

df1['P7 Rates'] = df7['P7 Rate'].values

df1['P7 SCAC'] = df7['P7 SCAC'].values

df1['P8 Rates'] = df8['P8 Rate'].values

df1['P8 SCAC'] = df8['P8 SCAC'].values

In [ ]:
df1

In [ ]:
df1.to_excel('Merkel_merged_fn.xlsx')

In [ ]:
merged = pd.concat([df1,df2,df3,df4,df5,df6])

In [ ]:
merged

In [ ]:
merged.to_excel('stevens_merged_out.xlsx')

In [ ]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas_source_files')

In [2]:
data = pd.read_excel('Pandas_source_files\LTL for LCL BID 4-19-24.xlsx')

rating = pd.read_excel('Pandas_source_files\Rating_Report_2024_04_22_11_29_36.xls')

In [3]:
data

,2024 LCL Pricing Worksheet,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,NaN,NaN,NaN,NaN,NaN,NaN,DESTINATION INFROAMTION,NaN,NaN,NaN,...,NaN,NaN,Destination Delivery,NaN,NaN,NaN,Destination Delivery,NaN,NaN,NaN
1,Lane,Service,Origin Port,Origin Country,US CFS,zip,Destination Door (Refer to address RFQ Locati...,zip,Destination Country,Carrier Suggested Routing,...,lbs per pallet,CLASS,Min,Cost per KILO W/M,MIN TARGET,PER KG TARGET,Min,Cost per KILO W/M,NTG Rate-Min,SCAC
2,1,PORT TO DOOR,HAIPHONG,VN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,NaN,...,1556.22285,65,NaN,NaN,99,0.15,0,0,NaN,NaN
3,2,PORT TO DOOR,HO CHI MINH,VN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,NaN,...,220.5,175,NaN,NaN,99,0.15,0,0,NaN,NaN
4,3,PORT TO DOOR,BUSAN,KR,NaN,NaN,ALEXANDRIA,NaN,US,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,80,PORT TO DOOR,SHANGHAI,CN,NaN,NaN,RICHMOND,NaN,CA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN
82,81,PORT TO DOOR,TOKYO,JP,NaN,NaN,RICHMOND,NaN,CA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN
83,82,PORT TO DOOR,XIAMEN,CN,NaN,NaN,RICHMOND,NaN,CA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN
84,83,PORT TO DOOR,YANTIAN,CN,NaN,NaN,RICHMOND,NaN,CA,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
data = data.iloc[1:]

In [5]:
data.rename(columns=data.iloc[0], inplace = True)

C:\Users\matthew.shuff\AppData\Local\Temp\ipykernel_18604\3079831275.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.rename(columns=data.iloc[0], inplace = True)

In [7]:
data = data.iloc[1:]

In [19]:
data = data.fillna(0)

In [20]:
data

,Lane,Service,Origin Port,Origin Country,US CFS,zip,Destination Door (Refer to address RFQ Location Tab),zip,Destination Country,Carrier Suggested Routing,...,lbs per pallet,CLASS,Min,Cost per KILO W/M,MIN TARGET,PER KG TARGET,Min,Cost per KILO W/M,NTG Rate-Min,SCAC
2,1,PORT TO DOOR,HAIPHONG,VN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,1556.22285,65,0,0,99.0,0.15,0,0,0,0
3,2,PORT TO DOOR,HO CHI MINH,VN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,220.50000,175,0,0,99.0,0.15,0,0,0,0
4,3,PORT TO DOOR,BUSAN,KR,0,0,ALEXANDRIA,0,US,0,...,0.00000,0,0,0,0.0,0.00,0,0,0,0
5,4,PORT TO DOOR,HONG KONG,HK,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,220.50000,175,0,0,99.0,0.15,0,0,0,0
6,5,PORT TO DOOR,KAOHSIUNG,TW,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,1470.00000,70,0,0,99.0,0.15,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,80,PORT TO DOOR,SHANGHAI,CN,0,0,RICHMOND,0,CA,0,...,0.00000,0,0,0,0.0,0.00,0,0,0,0
82,81,PORT TO DOOR,TOKYO,JP,0,0,RICHMOND,0,CA,0,...,0.00000,0,0,0,0.0,0.00,0,0,0,0
83,82,PORT TO DOOR,XIAMEN,CN,0,0,RICHMOND,0,CA,0,...,0.00000,0,0,0,0.0,0.00,0,0,0,0
84,83,PORT TO DOOR,YANTIAN,CN,0,0,RICHMOND,0,CA,0,...,0.00000,0,0,0,0.0,0.00,0,0,0,0
85,0,0,0,0,0,0,0,0,0,0,...,0.00000,.,0,0,0.0,0.00,0,0,0,0

In [21]:
data.Lane = data.Lane.apply(int)

In [9]:
rating

,OID,Primary Reference,Type,Lane ID,Carrier Name,Carrier SCAC,Contract Name,Contract Mode,Contract Service,Service Days,...,Total,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary
0,NaN,22,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
1,NaN,44,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
2,NaN,23,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
3,NaN,24,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
4,NaN,25,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
5,NaN,47,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
6,NaN,49,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
7,NaN,28,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
8,NaN,50,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
9,NaN,51,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
10,NaN,30,Carrier,NaN,FEDEX FREIGHT (ECONOMY),FXNL,FP FXNL LTL FXF501,LTL,Standard,2,...,209.23,209.23,442.00,75.18,0,-389.84,41.89,40,0,NaN
11,NaN,52,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
12,NaN,31,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
13,NaN,10,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
14,NaN,54,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
15,NaN,11,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
16,NaN,33,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
17,NaN,55,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
18,NaN,12,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
19,NaN,34,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
20,NaN,56,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
21,NaN,57,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
22,NaN,58,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
23,NaN,37,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
24,NaN,38,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
25,NaN,39,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
26,NaN,18,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
27,NaN,1,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
28,NaN,2,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
29,NaN,4,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
30,NaN,5,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
31,NaN,6,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
32,NaN,8,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
33,NaN,60,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
34,NaN,61,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
35,NaN,62,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
36,NaN,41,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
37,NaN,63,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
38,NaN,20,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
39,NaN,42,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
40,NaN,64,Carrier,NaN,OLD DOMINION FREIGHT LINE INC.,ODFL,FP ODFL LTL P44 CONTRACT,LTL,P44_STD,1,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
41,NaN,21,Carrier,NaN,TOTAL TRANSPORTATION & DISTRIBUTION INC,TOTL,FP TOTL LTL P44 CONTRACT,LTL,P44_STD,1,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
42,NaN,43,Carrier,NaN,"CENTRAL TRANSPORT INTERNATIONAL, INC.",CTII,FP CTII LTL P44 CONTRACT,LTL,P44_STD,1,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN

In [22]:
merged = data.merge(rating, left_on='Lane', right_on='Primary Reference')

In [23]:
merged

,Lane,Service,Origin Port,Origin Country,US CFS,zip,Destination Door (Refer to address RFQ Location Tab),zip,Destination Country,Carrier Suggested Routing,...,Total,Normalized Total,Item Total,Adjustment Total,Deficit Total,Discount Total,Fuel Total,Accessorial Total,Pct Accessorial Total,Accessorial Summary
0,1,PORT TO DOOR,HAIPHONG,VN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
1,2,PORT TO DOOR,HO CHI MINH,VN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
2,4,PORT TO DOOR,HONG KONG,HK,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
3,5,PORT TO DOOR,KAOHSIUNG,TW,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
4,6,PORT TO DOOR,KEELUNG,TW,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
5,8,PORT TO DOOR,MANILA,PH,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
6,10,PORT TO DOOR,NINGBO,CN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
7,11,PORT TO DOOR,SHANGHAI,CN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
8,12,PORT TO DOOR,YANTIAN,CN,"Elizabeth, NJ 07201",07201,"ALEXANDRIA, PA 16611",16611,US,0,...,84.98,84.98,72.63,0.00,0,0.00,12.35,0,0,NaN
9,18,PORT TO DOOR,BANGKOK,TH,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
10,20,PORT TO DOOR,FUZHOU,CN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
11,21,PORT TO DOOR,HAIPHONG,VN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
12,22,PORT TO DOOR,HO CHI MINH,VN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
13,23,PORT TO DOOR,HONG KONG,HK,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
14,24,PORT TO DOOR,KAOHSIUNG,TW,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
15,25,PORT TO DOOR,LAEM CHABANG,TH,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
16,28,PORT TO DOOR,NINGBO,CN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
17,30,PORT TO DOOR,QINGDAO,CN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,209.23,209.23,442.00,75.18,0,-389.84,41.89,40,0,NaN
18,31,PORT TO DOOR,SHANGHAI,CN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
19,33,PORT TO DOOR,XIAMEN,CN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
20,34,PORT TO DOOR,YANTIAN,CN,"Los Angeles, CA 90220",90220,"CARSON, CA 90810",90810,US,0,...,51.69,51.69,38.00,0.00,0,0.00,9.69,4,0,NaN
21,37,PORT TO DOOR,FUZHOU,CN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
22,38,PORT TO DOOR,HAIPHONG,VN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
23,39,PORT TO DOOR,HO CHI MINH,VN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
24,41,PORT TO DOOR,HONG KONG,HK,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
25,42,PORT TO DOOR,KAOHSIUNG,TW,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
26,43,PORT TO DOOR,KEELUNG,TW,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
27,44,PORT TO DOOR,LAEM CHABANG,TH,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
28,47,PORT TO DOOR,NINGBO,CN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
29,49,PORT TO DOOR,SHANGHAI,CN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
30,50,PORT TO DOOR,XIAMEN,CN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
31,51,PORT TO DOOR,XINGANG,CN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
32,52,PORT TO DOOR,YANTIAN,CN,"Elizabeth, NJ 07201",07201,"OGDENSBURG, NY 13669",13669,US,0,...,85.90,85.90,73.42,0.00,0,0.00,12.48,0,0,NaN
33,54,PORT TO DOOR,HAIPHONG,VN,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
34,55,PORT TO DOOR,HO CHI MINH,VN,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
35,56,PORT TO DOOR,HONG KONG,HK,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
36,57,PORT TO DOOR,KAOHSIUNG,TW,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
37,58,PORT TO DOOR,KEELUNG,TW,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
38,60,PORT TO DOOR,NINGBO,CN,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
39,61,PORT TO DOOR,SHANGHAI,CN,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
40,62,PORT TO DOOR,TAICHUNG,TW,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
41,63,PORT TO DOOR,XIAMEN,CN,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN
42,64,PORT TO DOOR,YANTIAN,CN,"Elizabeth, NJ 07201",07201,"SIDNEY, NY 13838",13838,US,0,...,122.01,122.01,107.50,0.00,0,0.00,14.51,0,0,NaN

In [26]:
merged.to_excel('lcl_bid.xlsx')

In [27]:
os.listdir(r'C:\Users\matthew.shuff\OneDrive - Nolan Transportation Group\Desktop\Pandas_source_files')

['2024 GRI List of US High Cost Service Areas Final (1).xlsx',
 'Echo-ADM-RRL 30 day_Anastasia Letosky.xlsx',
 'Farmer Brothers 2024 RFP LTL Rate Submission File (2).xlsx',
 'Farmer Brothers results (1).xlsx',
 'Freightview_shipments_5c672cb8a75f15000491c0d_Ahmos III Zu-Bolton.xlsx',
 'FWDA_HCD_src_fl.xlsx',
 'KING SOLOMON ENTERPRISES, INC._Anastasia Letosky.xlsx',
 'LTL for LCL BID 4-19-24.xlsx',
 'Marken LLP St. Pete LTL Pricing_Steven Dutton.xlsx',
 'MCG Data 11-1-23 thru 1-31-24 with NTG and exceptions (2).xlsx',
 'Moog CTSI LTL Data Nov 2023 thru Jan 2024 NTG results-exceptions.xlsx',
 'NTG PROPOSAL 3182024 (1).xlsx',
 'Rating_Report_2024_04_22_11_29_36.xls',
 'Rating_Report_true.xls',
 'S62B - LTL Volume Out 11 and 41_Kelsey Tapia.xlsx',
 'Shipping 04_03_2024_Kekoa Carville.xlsx',
 'Shipping 04_16_2024_Khalil Walker.xlsx',
 'True Fitness 2023 Data_Chi An Chen_4vs.xls',
 'zipsfor_myles_transport.xlsx']

In [3]:
df = pd.read_excel('Pandas_source_files/NTG PROPOSAL 3182024 (1).xlsx')

In [5]:
df.Ref.value_counts().head(60)

Ref
37087K4B0L3306     3
37087M1X1N5918     3
37087K4B0L3960     3
L4G0K206483405     2
L4L4S690670525     2
89113L5N6A6619     2
33781L4Z2H2725     2
L4L4S633069255     2
73179L8E2L8214     2
L4G0K210452405     2
60827L4W5B2165     2
33172M6R1R1133     2
L3R6E7851421079    2
78045M6K0E9300     2
37087L6Y5Z4612     2
27616K7S0C6440     2
33172K0K2G0420     2
35160L6T5R31458    2
30336L7N3G2175     2
37087L1Z1G1306     2
L5S1J770433220     2
M9W2Z428217221     2
37087L6Y5Z4320     2
02780N1K1E6310     2
75061K1G0Z6168     2
37087K4B0L3320     2
91342L5T2W9770     2
L6C0Y3333121485    2
K7P1T807036185     2
M6A2W120109204     2
37087M1X1N5320     2
15001L4K3S2400     2
73179N8X5E7196     1
89115L5T2H7722     1
41042M5V1J12052    1
48079K0K3E0155     1
23703L4L9J71400    1
27020K0M2T0300     1
60131L7E2Y4509     1
69101N0L2H0175     1
37087M1X1N5280     1
30721L5E1E1712     1
14210L4K4W8763     1
30121N1H6J2141     1
55445L4K3Z9291     1
14522L4Z1P3756     1
27292M8W1T2770     1
29916N1L0B9184     1
10457L8L8B7265     1
06776L8H3Z860      1
30336M9L1R2841     1
55379L0H1G0800     1
60517N0E1L0452     1
06051L5L5Z9300     1
23703M1X0A1870     1
30297L6Y0C996      1
30265L3R8T4301     1
69101K0A1L0155     1
55445L4K3Z9119     1
30121N4W3G9627     1
Name: count, dtype: int64